#!/bin/bash

# VBF Higgs to Invisible
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-Htoinv-mH110.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBFmH110 --sampleName Powheg-ggHtoinv-mH110 --numberOfJobs 1 --outputFolder MC_Powheg-Htoinv-mH110 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-Htoinv-mH125.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBFmH125 --sampleName Powheg-ggHtoinv-mH125 --numberOfJobs 1 --outputFolder MC_Powheg-Htoinv-mH125 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-Htoinv-mH150.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBFmH150 --sampleName Powheg-ggHtoinv-mH150 --numberOfJobs 1 --outputFolder MC_Powheg-Htoinv-mH150 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-Htoinv-mH200.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBFmH200 --sampleName Powheg-ggHtoinv-mH200 --numberOfJobs 1 --outputFolder MC_Powheg-Htoinv-mH200 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-Htoinv-mH300.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBFmH300 --sampleName Powheg-ggHtoinv-mH300 --numberOfJobs 1 --outputFolder MC_Powheg-Htoinv-mH300 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-Htoinv-mH400.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBFmH400 --sampleName Powheg-ggHtoinv-mH400 --numberOfJobs 1 --outputFolder MC_Powheg-Htoinv-mH400 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;

# Gluon Fusion Higgs to Invisible
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-ggHtoinv-mH110.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ggHmH110 --sampleName Powheg-ggHtoinv-mH110 --numberOfJobs 1 --outputFolder MC_Powheg-ggHtoinv-mH110 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-ggHtoinv-mH125.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ggHmH125 --sampleName Powheg-ggHtoinv-mH125 --numberOfJobs 1 --outputFolder MC_Powheg-ggHtoinv-mH125 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-ggHtoinv-mH150.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ggHmH150 --sampleName Powheg-ggHtoinv-mH150 --numberOfJobs 1 --outputFolder MC_Powheg-ggHtoinv-mH150 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-ggHtoinv-mH200.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ggHmH200 --sampleName Powheg-ggHtoinv-mH200 --numberOfJobs 1 --outputFolder MC_Powheg-ggHtoinv-mH200 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-ggHtoinv-mH300.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ggHmH300 --sampleName Powheg-ggHtoinv-mH300 --numberOfJobs 1 --outputFolder MC_Powheg-ggHtoinv-mH300 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Powheg-ggHtoinv-mH400.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ggHmH400 --sampleName Powheg-ggHtoinv-mH400 --numberOfJobs 1 --outputFolder MC_Powheg-ggHtoinv-mH400 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;

# WJets
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_WJetsToLNu-v1.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName WJetsToLNu_v1 --numberOfJobs 4  --outputFolder MC_WJetsToLNu-v1 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_WJetsToLNu-v2.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName WJetsToLNu_v2 --numberOfJobs 14 --outputFolder MC_WJetsToLNu-v2 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W1JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W1JetsToLNu   --numberOfJobs 6  --outputFolder MC_W1JetsToLNu   --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W2JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W2JetsToLNu   --numberOfJobs 8  --outputFolder MC_W2JetsToLNu   --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W3JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W3JetsToLNu   --numberOfJobs 4  --outputFolder MC_W3JetsToLNu   --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W4JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W4JetsToLNu   --numberOfJobs 4  --outputFolder MC_W4JetsToLNu   --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_EWK-W2jminus.dat  --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName EWK-W2jminus  --numberOfJobs 2  --outputFolder MC_EWK-W2jminus  --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_EWK-W2jplus.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName EWK-W2jplus   --numberOfJobs 2  --outputFolder MC_EWK-W2jplus   --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
# WJets -> electron
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_WJetsToLNu-v1.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName WJetsToLNu_v1 --numberOfJobs 4  --outputFolder MC_WJetsToLNu-v1_electron --fileCfg ../../test/MC/run_RegionElectronMET_electron_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_WJetsToLNu-v2.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName WJetsToLNu_v2 --numberOfJobs 14 --outputFolder MC_WJetsToLNu-v2_electron --fileCfg ../../test/MC/run_RegionElectronMET_electron_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W1JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W1JetsToLNu   --numberOfJobs 6  --outputFolder MC_W1JetsToLNu_electron   --fileCfg ../../test/MC/run_RegionElectronMET_electron_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W2JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W2JetsToLNu   --numberOfJobs 8  --outputFolder MC_W2JetsToLNu_electron   --fileCfg ../../test/MC/run_RegionElectronMET_electron_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W3JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W3JetsToLNu   --numberOfJobs 4  --outputFolder MC_W3JetsToLNu_electron   --fileCfg ../../test/MC/run_RegionElectronMET_electron_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W4JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W4JetsToLNu   --numberOfJobs 4  --outputFolder MC_W4JetsToLNu_electron   --fileCfg ../../test/MC/run_RegionElectronMET_electron_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_EWK-W2jminus.dat  --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName EWK-W2jminus  --numberOfJobs 2  --outputFolder MC_EWK-W2jminus_electron  --fileCfg ../../test/MC/run_RegionElectronMET_electron_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_EWK-W2jplus.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName EWK-W2jplus   --numberOfJobs 2  --outputFolder MC_EWK-W2jplus_electron   --fileCfg ../../test/MC/run_RegionElectronMET_electron_cfg.json;
# WJets -> muon
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_WJetsToLNu-v1.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName WJetsToLNu_v1 --numberOfJobs 4  --outputFolder MC_WJetsToLNu-v1_muon --fileCfg ../../test/MC/run_RegionElectronMET_muon_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_WJetsToLNu-v2.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName WJetsToLNu_v2 --numberOfJobs 14 --outputFolder MC_WJetsToLNu-v2_muon --fileCfg ../../test/MC/run_RegionElectronMET_muon_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W1JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W1JetsToLNu   --numberOfJobs 6  --outputFolder MC_W1JetsToLNu_muon   --fileCfg ../../test/MC/run_RegionElectronMET_muon_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W2JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W2JetsToLNu   --numberOfJobs 8  --outputFolder MC_W2JetsToLNu_muon   --fileCfg ../../test/MC/run_RegionElectronMET_muon_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W3JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W3JetsToLNu   --numberOfJobs 4  --outputFolder MC_W3JetsToLNu_muon   --fileCfg ../../test/MC/run_RegionElectronMET_muon_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W4JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W4JetsToLNu   --numberOfJobs 4  --outputFolder MC_W4JetsToLNu_muon   --fileCfg ../../test/MC/run_RegionElectronMET_muon_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_EWK-W2jminus.dat  --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName EWK-W2jminus  --numberOfJobs 2  --outputFolder MC_EWK-W2jminus_muon  --fileCfg ../../test/MC/run_RegionElectronMET_muon_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_EWK-W2jplus.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName EWK-W2jplus   --numberOfJobs 2  --outputFolder MC_EWK-W2jplus_muon   --fileCfg ../../test/MC/run_RegionElectronMET_muon_cfg.json;
# WJets -> tau
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_WJetsToLNu-v1.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName WJetsToLNu_v1 --numberOfJobs 4  --outputFolder MC_WJetsToLNu-v1_tau --fileCfg ../../test/MC/run_RegionElectronMET_tau_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_WJetsToLNu-v2.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName WJetsToLNu_v2 --numberOfJobs 14 --outputFolder MC_WJetsToLNu-v2_tau --fileCfg ../../test/MC/run_RegionElectronMET_tau_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W1JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W1JetsToLNu   --numberOfJobs 6  --outputFolder MC_W1JetsToLNu_tau   --fileCfg ../../test/MC/run_RegionElectronMET_tau_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W2JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W2JetsToLNu   --numberOfJobs 8  --outputFolder MC_W2JetsToLNu_tau   --fileCfg ../../test/MC/run_RegionElectronMET_tau_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W3JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W3JetsToLNu   --numberOfJobs 4  --outputFolder MC_W3JetsToLNu_tau   --fileCfg ../../test/MC/run_RegionElectronMET_tau_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_W4JetsToLNu.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName W4JetsToLNu   --numberOfJobs 4  --outputFolder MC_W4JetsToLNu_tau   --fileCfg ../../test/MC/run_RegionElectronMET_tau_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_EWK-W2jminus.dat  --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName EWK-W2jminus  --numberOfJobs 2  --outputFolder MC_EWK-W2jminus_tau  --fileCfg ../../test/MC/run_RegionElectronMET_tau_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_EWK-W2jplus.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup WJets --sampleName EWK-W2jplus   --numberOfJobs 2  --outputFolder MC_EWK-W2jplus_tau   --fileCfg ../../test/MC/run_RegionElectronMET_tau_cfg.json;

# Z/Z* to leptons samples
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_DYJetsToLL_PtZ-100-madgraph.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_ll --sampleName DYJetsToLL_PtZ-100-madgraph --numberOfJobs 1 --outputFolder MC_DYJetsToLL_PtZ-100-madgraph --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_DYJetsToLL.dat                  --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_ll --sampleName DYJetsToLL       --numberOfJobs 8 --outputFolder MC_DYJetsToLL         --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_DY1JetsToLL.dat                 --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_ll --sampleName DY1JetsToLL      --numberOfJobs 6 --outputFolder MC_DY1JetsToLL        --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_DY2JetsToLL.dat                 --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_ll --sampleName DY2JetsToLL      --numberOfJobs 6 --outputFolder MC_DY2JetsToLL        --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_DY3JetsToLL.dat                 --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_ll --sampleName DY3JetsToLL      --numberOfJobs 4 --outputFolder MC_DY3JetsToLL        --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_DY4JetsToLL.dat                 --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_ll --sampleName DY4JetsToLL      --numberOfJobs 2 --outputFolder MC_DY4JetsToLL        --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_EWK-Z2j.dat                     --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_ll --sampleName EWK-Z2j          --numberOfJobs 1 --outputFolder MC_EWK-Z2j            --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;

# Z/Z* to nu nu samples
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_ZJetsToNuNu_50_HT_100.dat  --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_nunu --sampleName ZJetsToNuNu_50_HT_100  --numberOfJobs 1 --outputFolder MC_ZJetsToNuNu_50_HT_100  --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_ZJetsToNuNu_100_HT_200.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_nunu --sampleName ZJetsToNuNu_100_HT_200 --numberOfJobs 1 --outputFolder MC_ZJetsToNuNu_100_HT_200 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_ZJetsToNuNu_200_HT_400.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_nunu --sampleName ZJetsToNuNu_200_HT_400 --numberOfJobs 1 --outputFolder MC_ZJetsToNuNu_200_HT_400 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_ZJetsToNuNu_400_HT_inf.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup ZJets_nunu --sampleName ZJetsToNuNu_400_HT_inf --numberOfJobs 1 --outputFolder MC_ZJetsToNuNu_400_HT_inf --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;

# VV samples
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_WW-pythia6-tauola.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VV --sampleName WW --numberOfJobs 2 --outputFolder MC_WW --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_WZ-pythia6-tauola.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VV --sampleName WZ --numberOfJobs 2 --outputFolder MC_WZ --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_ZZ-pythia6-tauola.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VV --sampleName ZZ --numberOfJobs 2 --outputFolder MC_ZZ --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;

# Single top samples
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_SingleT-s-powheg-tauola.dat    --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup SingleTop --sampleName SingleT-s    --numberOfJobs 1 --outputFolder MC_SingleT-s    --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_SingleT-t-powheg-tauola.dat    --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup SingleTop --sampleName SingleT-t    --numberOfJobs 1 --outputFolder MC_SingleT-t    --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_SingleTBar-s-powheg-tauola.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup SingleTop --sampleName SingleTBar-s --numberOfJobs 1 --outputFolder MC_SingleTBar-s --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_SingleTBar-t-powheg-tauola.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup SingleTop --sampleName SingleTBar-t --numberOfJobs 1 --outputFolder MC_SingleTBar-t --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_T-tW.dat                       --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup SingleTop --sampleName T-tW         --numberOfJobs 1 --outputFolder MC_T-tW         --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_Tbar-tW.dat                    --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup SingleTop --sampleName Tbar-tW      --numberOfJobs 1 --outputFolder MC_Tbar-tW      --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;

# TTbar samples
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_TTJets.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup TTbar --sampleName TTJets --numberOfJobs 2 --outputFolder MC_TTJets --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;

# Inclusive QCD Samples
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-30to50-pythia6.dat     --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-30to50     --numberOfJobs 2 --outputFolder MC_QCD-Pt-30to50     --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-50to80-pythia6.dat     --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-50to80     --numberOfJobs 2 --outputFolder MC_QCD-Pt-50to80     --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-80to120-pythia6.dat    --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-80to120    --numberOfJobs 2 --outputFolder MC_QCD-Pt-80to120    --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-120to170-pythia6.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-120to170   --numberOfJobs 2 --outputFolder MC_QCD-Pt-120to170   --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-170to300-pythia6.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-170to300   --numberOfJobs 1 --outputFolder MC_QCD-Pt-170to300   --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-300to470-pythia6.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-300to470   --numberOfJobs 1 --outputFolder MC_QCD-Pt-300to470   --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-470to600-pythia6.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-470to600   --numberOfJobs 1 --outputFolder MC_QCD-Pt-470to600   --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-600to800-pythia6.dat   --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-600to800   --numberOfJobs 1 --outputFolder MC_QCD-Pt-600to800   --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-800to1000-pythia6.dat  --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-800to1000  --numberOfJobs 1 --outputFolder MC_QCD-Pt-800to1000  --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-1000to1400-pythia6.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-1000to1400 --numberOfJobs 1 --outputFolder MC_QCD-Pt-1000to1400 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-1400to1800-pythia6.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-1400to1800 --numberOfJobs 1 --outputFolder MC_QCD-Pt-1400to1800 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-1800-pythia6.dat       --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup QCD --sampleName QCD-Pt-1800       --numberOfJobs 1 --outputFolder MC_QCD-Pt-1800       --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;

# VBF QCD Samples
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-80to120_VBF-MET40.dat  --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBF-QCD --sampleName VBF-QCD-Pt-80to120  --numberOfJobs 1 --outputFolder MC_QCD-Pt-80to120_VBF-MET40  --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-120to170_VBF-MET40.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBF-QCD --sampleName VBF-QCD-Pt-120to170 --numberOfJobs 1 --outputFolder MC_QCD-Pt-120to170_VBF-MET40 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-170to300_VBF-MET40.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBF-QCD --sampleName VBF-QCD-Pt-170to300 --numberOfJobs 1 --outputFolder MC_QCD-Pt-170to300_VBF-MET40 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-300to470_VBF-MET40.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBF-QCD --sampleName VBF-QCD-Pt-300to470 --numberOfJobs 1 --outputFolder MC_QCD-Pt-300to470_VBF-MET40 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MC_QCD-Pt-470to600_VBF-MET40.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MC --sampleType MC --sampleGroup VBF-QCD --sampleName VBF-QCD-Pt-470to600 --numberOfJobs 1 --outputFolder MC_QCD-Pt-470to600_VBF-MET40 --fileCfg ../../test/MC/run_RegionElectronMET_cfg.json;

# Prompt Data 
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MET_MET-2012A-22Jan2013-v1.dat       --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MET --sampleType Data --sampleGroup PromptMET --sampleName PromptRunA --numberOfJobs 2 --outputFolder DATA_MET-2012A-22Jan2013-v1 --fileCfg ../../test/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MET_MET-2012B-22Jan2013-v1.dat       --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MET --sampleType Data --sampleGroup PromptMET --sampleName PromptRunB --numberOfJobs 4 --outputFolder DATA_MET-2012B-22Jan2013-v1 --fileCfg ../../test/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MET_MET-2012C-22Jan2013-v1.dat       --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MET --sampleType Data --sampleGroup PromptMET --sampleName PromptRunC --numberOfJobs 6 --outputFolder DATA_MET-2012C-22Jan2013-v1 --fileCfg ../../test/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/MET_METParked-2012D-22Jan2013-v1.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/MET --sampleType Data --sampleGroup PromptMET --sampleName PromptRunD --numberOfJobs 28 --outputFolder DATA_MET-2012D-22Jan2013-v1 --fileCfg ../../test/run_RegionElectronMET_cfg.json;

# Parked Data
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/PARKED_VBF-Parked-2012B-22Jan2013-v1.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/PARKED --sampleType Data --sampleGroup Parked --sampleName ParkedRunB --numberOfJobs 44 --outputFolder DATA_VBF-Parked-2012B-22Jan2013-v1 --fileCfg ../../test/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/PARKED_VBF-Parked-2012C-22Jan2013-v1.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/PARKED --sampleType Data --sampleGroup Parked --sampleName ParkedRunC --numberOfJobs 80 --outputFolder DATA_VBF-Parked-2012C-22Jan2013-v1 --fileCfg ../../test/run_RegionElectronMET_cfg.json;
python ../../../../../bin/hepfwMakeBatchJobs.py --fileList ../../../Samples/filelists/2013Dec18/PARKED_VBF-Parked-2012D-22Jan2013-v1.dat --filePrefix root://xrootd.grid.hep.ph.ic.ac.uk//store/user/pdunne/Dec18/PARKED --sampleType Data --sampleGroup Parked --sampleName ParkedRunD --numberOfJobs 84 --outputFolder DATA_VBF-Parked-2012D-22Jan2013-v1 --fileCfg ../../test/run_RegionElectronMET_cfg.json;
